### ISSUE TITLE
Default value not accepted for idpmetadata field

### ISSUE THREAD

**Issue by azrek** [catalyst/moodle-auth_saml2#122]
Moodle version: 2017051500.10
DB: psql (PostgreSQL) 9.5.7
OS: Linux 16.04
Plugin version: 2017051800 (MOODLE_33PLUS branch)

Post update of the plugin, it insists on having a value in the field IdP metadata xml OR public xml URL (auth_saml2 | idpmetadata). The default value of blank is not accepted. It comes up with the error:

'The IdP XML isn't valid'

The problem is that the plugin is not even enabled.

**Comment by brendanheywood** [comment]
This need 3 unit tests:

* [ ] if the field is blank then it should be considered valid
* [ ] if the field has data in it, but it doesn't parse then it should not be consider valid
* [ ] if the field has urls in it, and they don't curl / parse, then it should not be valid

I don't think we should worry about whether the plugin is enabled or not, because it's nice to be able to configure the plugin while it is off and then turn it on. But happy to adopt how all other auth plugins work in this request in core, I think this changed in 3.3 (previously the settings could not be accessed, but now they can be)

**Comment by roperto** [comment]
It now accepts empty, XML or URLs (with multi idp support)
