### ISSUE TITLE
Old sesskey when SAML2 performs the login without refresh.

### ISSUE THREAD

**Issue by roperto** [catalyst/moodle-auth_saml2#131]
**What happened?**

When using an AJAX, such as complete an activity progress in a course, if the session expires (emulate that by deleting the MoodleSession cookie) then we get an ajax error.

The problem is: after logging in, a new sesskey is generated which differs from the one used in Ajax.

**Possible solution:**

When logging in on the background, reuse the previous sesskey instead of generating a new one (use the one from the query). Could it be a potential security issue? Yes...

**Security issue:**

In theory we can use this to reset the sesskey to any value we want, but that can only be exploited if you are authenticated by the IDP. If you receive a link in a email making a request to the site, the IDP may auto-authenticate the user and ignore the sesskey, allowing the link to perform any action.

This goes hand-to-hand with the issue where moodle does not respect the action verbs.

**Note:**

This is a general Moodle issue (the way security is structured), any other auth plugin including Moodle basic/manual will present the same problem.

**Comment by brendanheywood** [comment]
Yeah this is completely out of scope of the auth plugin. The proper fix is more like moodle properly handling the sesskey check at a generic level and saying something like 'you session might have expired please reload', and if they reload and it works then all good, otherwise they will get redirected to the login page.

Doing anything other than this will be a security vector, and doing anything inside this plugin is the wrong place to do it.
