### ISSUE TITLE
Settings UI is not available

### ISSUE THREAD

**Issue by markmartin1** [catalyst/moodle-auth_saml2#173]
I've installed saml2 on moodle 3.3.1 and it's not appearing in the Admin - Plugins/Authentication menu. It does appear in the Plugins Overview list as Enabled but there is no Settings link. 
Any ideas would be appreciated. Is moodle 3.3.1 supported? 

Thanks in advance,

Mark

**Comment by mattporritt** [comment]
Hi Mark,
This is a common issue with using the 3.2 version of the plugin on Moodle 3.3 and above. This is due to core changes in Moodle 3.3.
The Moodle Plugin directory now contains updated versions of the plugin. There are two versions available, one for Moodles up to and including V 3.2 and another one for Moodle versions 3.3 and above.
Download the version of the plugin for Moodle 3.3 and above either from the plugin directory: https://moodle.org/plugins/pluginversions.php?plugin=auth_saml2 or from here on the Moodle 3.3 branch: https://github.com/catalyst/moodle-auth_saml2/tree/MOODLE_33PLUS

Cheers,
Matt Porritt

**Comment by markmartin1** [comment]
Thanks Matt, much appreciated.

**Comment by roperto** [comment]
Please disregard the commits above, they referenced the wrong issue.
