### ISSUE TITLE
The url didn't return any data

### ISSUE THREAD

**Issue by aashline** [catalyst/moodle-auth_saml2#207]
**What happened?**
Upgraded Moodle to latest 3.4 and upgraded your plugin.  Now getting the error: The url didn't return any data"  

Can't change field value for Display IdP link because it throws this error when I try to do so.

Please provide as many of the following as applies:
* stacktrace of the error
* screen shots
* a dump of the error log with both moodle debugging on full and saml debugging on as well

**What you expected:**
to be able to save the changes and log out and test the upgraded plugin.  Unable to do so.

**Comment by aashline** [comment]
![saml2_issue](https://user-images.githubusercontent.com/34070452/36980746-3d1e2922-2059-11e8-945b-a7dd1c4d9d16.jpg)

**Comment by roperto** [comment]
Hi Aashline.

Is the metadata accessible by the Moodle server?

From here I could not view https://tadfs.revenuepremier.com/FederationMetadata/2007-06/FederationMetadata.xml

An alternative, if it is not accessible, would be to copy the contents of that XML and paste in that field instead of the URL.

Cheers

Daniel

**Comment by roperto** [comment]
I'm closing this as it seems like a networking issue. If you are still experiencing it please reopen here.
