### ISSUE TITLE
issue with php5.5 lint

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-auth_saml2#214]
TASK [deploy_code : show PHP lint results] *************************************
ok: [] => {
    "php_lint.stderr_lines": [
        "PHP Parse error:  syntax error, unexpected '.' in auth/saml2/tests/behat/behat_auth_saml2.php on line 234",
        "xargs: /usr/bin/php5: exited with status 255; aborting"
    ]
}

https://github.com/catalyst/moodle-auth_saml2/blob/master/tests/behat/behat_auth_saml2.php#L234

**Comment by danmarsden** [comment]
we should probably fix this to work with php 5.5 or create branches in github for each supported release with differing php support.

**Comment by roperto** [comment]
```php
// The Splat Operator ...
return $object->$method(...$params);

// ... reads much better than that.
return call_user_func_array([$object, $method], $params);
```

But oh, well... I'll update it for those who are stuck into 5.4  ...

**Comment by danmarsden** [comment]
yeah - probably more important since that block of code is supposed to run on older 2.8/2.7 sites which are more likely to be running php 5.5...

**Comment by danmarsden** [comment]
probably good to have a deprecation path for that code though... building support for multiple branches using workarounds like this becomes problematic in future.

**Comment by roperto** [comment]
Actually we just merged back the branches because we were not deprecating them. I think that would work great if we actually stopped updating supporting a version of Moodle, then we could freeze the branch as it was and leave it as unsupported.

As of now we are getting a lot of work on Moodle 27~29 because of Totara, meaning we have to "forward-port" fixes and changes to the newer branches (we had 4 versions) and things were getting forgotten. I never had a PHP 5.5 install before (which would scare me) but the CI is running for PHP 5.5 now so should catch syntax issues easily.

That way to call a function by name is documented in PHP, should not be depracated easily, it is just ugly to read:

> A method of an instantiated object is passed as an array containing an object at index 0 and the method name at index 1. Accessing protected and private methods from within a class is allowed.

http://php.net/manual/en/language.types.callable.php

**Comment by danmarsden** [comment]
yeah - merging branches can help in the short-term but makes it much harder in the longer term - I'd advise against it and just make sure you remember to backport to supported releases. It makes the technical debt grow really quickly.

Turnitin have been trying to manage this with a single branch in their moodle plugins but are starting to run into bigger issues now with all the little work-arounds.
