### ISSUE TITLE
Own auth:saml2 username change bug

### ISSUE THREAD

**Issue by ssllqq** [catalyst/moodle-auth_saml2#278]
User with manager permissions on system, can update own username if auth type is saml2
It works only from site administration /admin/user.php

Moodle 3.5.1 (Build: 20180709)
auth_saml2 | 2018071100

![image](https://user-images.githubusercontent.com/6871405/44468107-25a35380-a62d-11e8-8561-583f202d42a6.png)

**Comment by danmarsden** [comment]
I'm not sure this is really a bug with the saml2 plugin - I'm pretty sure the manager role change their username no matter what auth method is selected. - Admins users need this capability because occasionally usernames change in the external system - can happen a lot when staff get married/surnames change etc.
I'm not sure we should (or can) do anything about this in the saml plugin code. (I haven't checked this though, so if you are aware of other auth plugins that prevent the manager from changing their own username in Moodle please let us know.)

**Comment by ssllqq** [comment]
I see it will be problem in core because editadvanced_form.php it does not match this condition for own profile
if ($userid !== -1) {
     $mform->disabledIf('username', 'auth', 'in', $cannotchangeusername);
}

**Comment by danmarsden** [comment]
yes - as mentioned I do not think this is actually a bug. Manager and admin roles have the capability to change all user profile fields (including username.)

**Comment by jprovasnik** [comment]
I feel like I have the opposite issue, as site admin, I can 'not' edit a username with a SAML2 authentication on Moodle 3.9 (and that is the expected behavior you are indicating here correct?)
