### ISSUE TITLE
Resource hidden when accessing directly prior to SAML login

### ISSUE THREAD

**Issue by deanmaunder** [catalyst/moodle-auth_saml2#300]
When directly accessing a deep link to a course resource, prior to logging in via SAML2, Moodle shows the resource to be 'hidden' then redirects to the course page.  The resource can then be accessed directly.
Tested in Moodle 3.0.1
To replicate:
Log into Moodle via SAML2
Access a course
Copy the URL to a resource (PDF, PPT etc)
Log out of Moodle
Past copied URL in browser
Log in via SAML2

*Expected result*
Resource downloads or opens as appropriate

*Actual result*
Moodle shows 
![image](https://user-images.githubusercontent.com/2639446/49619664-43909a80-fa09-11e8-962d-8a0158d31564.png)

Then redirects to course page

**Comment by danmarsden** [comment]
this sounds like an issue with core moodle setting a different wantsurl. Also - Moodle 3.0 is not supported any more and Moodle 3.1 is only supported until May for security issues. (not bug fixes.) - I'm closing this as won't fix because I don't think it is an issue with the saml2 plugin, and also because it is reported against an unsupported Moodle release. Please update to a recent supported version of Moodle. If you find that some likes work fine (like course url etc) but you are still having an issue with resources thiablys is probably not something we can fix within the saml2 pugin. I would suggest testing

**Comment by deanmaunder** [comment]
Hi @danmarsden we have also tested this with SAML2 against 3.4 with the same issue.
I will see if the same issue presents with a core auth method

**Comment by danmarsden** [comment]
I just had a quick look at the file serving code in Moodle (via the file.php page) - The require_login call (which is responsible for setting wantsurl) is explicitly called with setwantsurl to false - so this is really "expected" Moodle behaviour.

**Comment by brendanheywood** [comment]
Is guest mode / auto login as guest enabled here? And is forcelogin on?

The pre_loginpage_hook which saml leverages fires inside require_login() here:

https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L2693

but there are a couple edge cases where require_login() can redirect them before that hook fires:

https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L2665

**Comment by brendanheywood** [comment]
I've just tried to reproduce this locally and cannot reproduce it with either guest mode on or off, or auto login on or off. In all cases it does what I expect, redirects to the login page, I login and then it redirects back to the pluginfile.php and serves it:

http://moodle.local/pluginfile.php/11904/mod_resource/content/1/foobar.pdf

**Comment by deanmaunder** [comment]
Are you testing as a non-admin user?  
If a site admin logs in it works fine, its only when a non admin user logs in the $cm->uservisible is set to false.

If I dump the variable and exit at the point in the code, then refresh the page it works, so it seems like a race condition of some sort.

**Comment by deanmaunder** [comment]
I found the place where it was throwing the hidden activity exception and dumped the variable there
![image](https://user-images.githubusercontent.com/2639446/49757302-d5e5b680-fd07-11e8-9e4b-45a0f3fd98d1.png)

I added a 'return true;' at the start of the pre_loginpage_hook() and that has stopped the issue from occurring

**Comment by brendanheywood** [comment]
Ok as another test can you please remove the return true hack and try this in core instead:

```php
diff --git a/lib/moodlelib.php b/lib/moodlelib.php
index 9ba9f3934e5..82aec749dc6 100644
--- a/lib/moodlelib.php
+++ b/lib/moodlelib.php
@@ -2616,6 +2616,9 @@ function require_login($courseorid = null, $autologinguest = true, $cm = null, $
                 $authplugin = get_auth_plugin($authname);
                 $authplugin->pre_loginpage_hook();
                 if (isloggedin()) {
+                    if ($course) {
+                        get_fast_modinfo($course, 0, true);
+                    }
                     break;
                 }
             }
```

**Comment by deanmaunder** [comment]
Updated as per above and I get 'Activity is hidden'

**Comment by brendanheywood** [comment]
Ok I'll reopen this. I think @danmarsden is right that it will ultimately end up in core but we'll try to reproduce this and patch it where it needs to be patched. I will also create a new saml specific setting which toggles the pre_loginpage_hook, there have been a few instances of bugs with that so it would be good to quickly turn it off while in prod while the root cause it sorted out.

**Comment by ilya-catalyst** [comment]
Just an update - I was able to repclicate the issue only with Dual login set to No

**Comment by ilya-catalyst** [comment]
I have created an issue in Moodle tracker https://tracker.moodle.org/browse/MDL-64439

**Comment by brendanheywood** [comment]
FYI that tracker was just integrated as a bug fix and will flow out into core shortly.
