### ISSUE TITLE
Test functionality not working in Moodle 3.6

### ISSUE THREAD

**Issue by jtsafran** [catalyst/moodle-auth_saml2#322]
When trying to use the test functionality from Manage Authentication, no IdPs show in the list to test.  Using the direct link (https://<URL>/auth/saml2/test.php?login=true), we get the following error:

Exception - Could not find the metadata of an IdP with entity ID '<random id>'

Debug info: 
Error code: generalexceptionmessage

×Stack trace:
line 135 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: SimpleSAML_Error_Exception thrown
line 328 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->getIdPMetadata()
line 431 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->startSSO()
line 193 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Source.php: call to sspmod_saml_Auth_Source_SP->authenticate()
line 161 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML_Auth_Source->initLogin()
line 103 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Simple->login()
line 72 of /auth/saml2/test.php: call to SimpleSAML\Auth\Simple->requireAuth()

However, if you display the IdP button, the site will go to the SSO (ADFS in this case) without issue.

Not a total showstopper, but the testing is awesome for making sure you get the Attributes mapped correctly :-)

Thanks!
-Jesse

**Comment by leonstr** [comment]
I've added a pull request which fixes this for me (tested with Moodle 3.6 and 3.7). I've only tested with XML in **auth_saml2 | idpmetadata** not a metadata URL (I get "Invalid metadata" so I'm probably doing it wrong).

There were nested **foreach** loops in **classes/form/testidpselect.php:definition()** which didn't seem to match the structure of the arrays returned by **locallib.php:auth_sam2_get_idps()** so I've removed these and just passed **_entityid_ => _name_** which appears to populate the IdP drop-down as expected. I don't know if I've just removed 10+ lines I shouldn't have just because I don't understand them and actually they were important.

**Comment by LoveBug** [comment]
It looks like this issue also impacts version 3.5, Leons patch looks promising so I will be testing it shortly.

**Comment by LoveBug** [comment]
I've tested Leons patch and it resolves the issue. 
 Additionally this bug also effects the 27-34 branch and any fix will need to be backported there as well.

**Comment by brendanheywood** [comment]
Pretty sure this is already fixed
