### ISSUE TITLE
Not a valid IdP for this SP

### ISSUE THREAD

**Issue by callumlew** [catalyst/moodle-auth_saml2#324]
Hi,

After upgrading from Moodle 3.1 -> 3.5 and upgrading the saml2 plugin from version: 2018071100 -> version : 2019022100 we are receiving the below error message:

> SAML2 exception: Cannot retrieve metadata for IdP "http://www.okta.com/*string*" because it isn't a valid IdP for this SP

This was not appearing before the upgrade.

There is the option to click Continue, when you click continue then you progress to the site with all the correct details. 

Has any one seen this error before? Is this something that has been added recently?

Thanks in advance

**Comment by jtsafran** [comment]
I have seen this, as well, but it was only impacting a few users.  To "fix" it, we:

1) Set a default IdP (the plugin looks like it should default if there is only one, but I explicitly set it, just in case)
2) Re-saved all of the settings in the plugin
3) Purged the site cache

And I have not had any more complaints, since.  Might be worth a shot.

**Comment by rklingaman** [comment]
I'm seeing this as well once I got upgraded to 3.7 but can't git rid of it. Only comes up from an IDP initiated login from our IDP which is Okta. I have also updated my plugin to match the master branch so that it was the most current but doesn't seem to fix it.

Also the Alternative Logout URL is not redirecting correctly just keeps them logged in.

**Comment by rklingaman** [comment]
I followed this issue:

https://github.com/catalyst/moodle-auth_saml2/issues/338

Wasn't sure about how to do the patch but I change line 43 to remove md5 and it fixed my issue with the valid IDP.

**Comment by dmitriim** [comment]
Hi all, 
Have you tried to resave config of the plugin? Does it fix the issue?
It seems like it's related to https://github.com/catalyst/moodle-auth_saml2/issues/362

**Comment by brendanheywood** [comment]
Reasonably sure this is a duplicate and it's fixed now
