### ISSUE TITLE
Logging back in after logging out with Attempt IdP Signout set to No seems to allow you to log back in without checking the IdP for your session state

### ISSUE THREAD

**Issue by jstilwell** [catalyst/moodle-auth_saml2#499]
First of all, I love your plugin. Thank you for maintaining it.

I discovered a fairly weird problem that I think may be a bug.

If you login to Moodle via SAML and then log out with Attempt IdP Signout set to No, when you click the SAML login button, it signs you back in. This is expected behavior.  However, if you manually log out of your IdP and then click Moodle's SAML login button again, it will still log you right back in.

If you do this with a SAML tracer extension on, you will see that when you click the SAML login button, there's no communication back to the IdP.

What I discovered is  that somehow your authenticated state is bound to the browser state in some way I haven't found yet, because if you logout of Moodle again, close the browser completely and reopen it, and then click to login to Moodle via SAML, it will redirect you to the IdP.

This seems like a substantial bug for scenarios where a computer may be shared by multiple users.

**Comment by brendanheywood** [comment]
There are 3 sessions, the idp session, the sp session, and the moodle session. The sp one in the middle is mostly invisible but I think is the issue here. When that setting is off it logs you out of moodle, but does not attempt to log you out of the sp or the idp. But it probably should still log you out of the sp. As a quick test, reproduce it and then just before you try the re-login, look at the cookies and delete the MDL_SSP_SessID cookie which will kill the middle session.

Probably the easiest approach is manually kill that cookie on moodle logout when the setting is off. Another approach is if that setting is off then the session length for the SP session can be very short. Pull requests welcome or if you'd like to sponsor this fix please contact us and reference this issue https://www.catalyst-au.net/contact-us/sydney#email-us

**Comment by badgerhill** [comment]
Had the same issue. Easy fix
in auth.php look for  public function logoutpage_hook() 

after line 1003 
1002 // Only log out of the IdP if we logged in via the IdP. TODO check session timeouts.
1003       if ($auth->isAuthenticated()) {
add these lines to delete the cookie

` $myCookie = 'MOODLEIDP1_'.$CFG->sessioncookie;`
`setcookie($myCookie, '', time() - HOURSECS, $CFG->sessioncookiepath, $CFG->sessioncookiedomain,
  $cookiesecure, $CFG->cookiehttponly);`

**Comment by brendanheywood** [comment]
thanks @badgerhill - are you able to sort that into a  pull request please?

**Comment by jstilwell** [comment]
Just wanted to check back in to see if there was a fix possible for this issue?

**Comment by jstilwell** [comment]
Being the squeaky wheel again, but is there a possible fix for this bug?  It seems like it would be a security concern.

**Comment by brendanheywood** [comment]
thanks for the nudge @jstilwell this should be fixed now please test away
