### ISSUE TITLE
Potential for multiple IdPs?

### ISSUE THREAD

**Issue by amazon750** [catalyst/moodle-auth_saml2#5]
I'm just wondering if it's either currently possible, but not documented, or easily implementable, to have more than one IdP set up with this plugin.

**Comment by brendanheywood** [comment]
This isn't currently supported but I did think about this while implementing it. It would be fairly easy to implement this in one or both of these two ways:

* have the idp url field accept multiple urls
* support the case when the idp xml metadata contains multiple ```<IDPSSODescriptor>``` elements

You would then see a login link for each IdP on the login page. There are a few caveats:

* All the config would apply to all the IdP's, it would be a lot more work to add UI and logic to have config per IdP. Importantly they'd have to have the same attribute mappings for account auto creation.
* The identities that the various IdP's would provide should be mutually exclusive, other wise you'd get weird things like a person logging into someone else's account if they had the same username.
* Identities from all the IdP's would have the same auth type inside moodle. We could add some config so that the IdP url gets added to a user profile field or something like that so you can tell them apart.
* We'd have to sort a little bit of logic to correctly label the different logins if the IdP metadata doesn't return it's label in a ```<mdui:DisplayName>``` element

I would be much better if moodle itself supported adding multiple instances of each auth plugin, but that's a deep architectural change which will probably never land.

This is a bit of an edge case feature so it probably wouldn't be implemented any time soon - unless you wanted to sponsor the work.

**Comment by amazon750** [comment]
Thanks Brendan,

We are indeed interested in sponsoring, let me know how to proceed.

**Comment by brendanheywood** [comment]
Great! Email me at brendan@catalyst-au.net and we'll get that ball rolling :)

**Comment by praj** [comment]
Hi Brendan,

This has come up before for me as well, and would like to see a solution for this, so let me know if there is anything I can do to help.

At a high-level is this largely about adding more entries in authsources.php or is it more complicated than that?

**Comment by brendanheywood** [comment]
thanks @praj - yes conceptually it's just about taking the info from the moodle gui config and turning it into entries in the auth sources file. No real complications just testing and handling various few edge cases. If you want to submit a pull request or sponsor us to write it, either is welcome

**Comment by fbuland** [comment]
@brendanheywood,
Our needs:
- support the case when the idp xml metadata contains multiple `<IDPSSODescriptor>` elements
- All the config would apply to all the IdP's
-  Identities from all the IdP's have the same auth type inside moodle
- IdP metadata return it's label in a `<mdui:DisplayName>` element

We can sponsor the development. I will email you at brendan@catalyst-au.net

**Comment by sam-suresh** [comment]
Hi 
Is this feature was added? I'm looking at possibility to allow 2 SAML2 instances. 
Is there any workaround for this?

Sam

**Comment by maxwst** [comment]
Hi,
I have integrated your MOODLE_33PLUS-multiidp branch into our moodle and have attempted to set up multiple okta Idps using the xml URLs provided by two different Okta Accounts.
When my users try to login the get the following error, from one of the Idps
Exception - Cannot retrieve metadata for IdP 'http://www.okta.com/exkcqze8wjkoVajO30h7' because it isn't a valid IdP for this SP.

More information about this error

Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 112 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: SimpleSAML_Error_Exception thrown
line 116 of /auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php: call to sspmod_saml_Auth_Source_SP->getIdPMetadata()
line 30 of /auth/saml2/sp/saml2-acs.php: call to require()

I believe I have followd the set up instructions in your README and on the moodle SAML2 configuration page.
I guess this is most probably a configurate step I'm missing, could you please put me out of my misery.
Thanks

**Comment by brendanheywood** [comment]
@maxwst when I go to that url, I first get a redirect to the https version but also with a / on the end, and then after the redirect I get a 404. When you visit the IdP's metadata url you should get a big chunk of xml.

**Comment by maxwst** [comment]
Hi Brendan,

Sorry the error message doesn’t give the full URL it is

https://dev-513907.oktapreview.com/app/exkchebssmoCwYVBh0h7/sso/saml/metadata

Regards

Steve

**Comment by brendanheywood** [comment]
@maxwst there is a lot of unknowns here, and it will be hard for us to debug this without knowing more. If you would like commercial support please contact us: https://www.catalyst-au.net/content/contact-us

**Comment by roperto** [comment]
Implemented in version 2018021903.
