### ISSUE TITLE
"Exception - Unable to load private key from file" error on Moodle 3.10

### ISSUE THREAD

**Issue by isotopeee** [catalyst/moodle-auth_saml2#539]
**What happened?**

I'm trying to integrate this plugin with Auth0 and I haven't succeeded so far.

Here's the error I'm getting when I've tried to debug via the test page:

![ec2-3-1-165-206 ap-southeast-1 compute amazonaws com_auth_saml2_test php(Laptop with HiDPI screen) (2)](https://user-images.githubusercontent.com/17417116/115119496-37567800-9fdb-11eb-8d13-12c876458b01.png)

In response to the error above, I've checked the `moodledata/saml2/` directory and `ec2-3-1-165-206.ap-southeast-1.compute.amazonaws.com.pem` is indeed missing. So I've tried to manually create `ec2-3-1-165-206.ap-southeast-1.compute.amazonaws.com.pem` via `touch` and try "Regenerate certificate" via the SAML2 settings page but no luck.

I've also tried to set the directory permission via `chmod -R 777 moodledata` but still no luck.

Environment:
Moodle: `3.10`
SAML2 plugin version: `auth_saml2_moodle37_2019110701`
Hosting: AWS EC2 (via Bitnami LMS powered by Moodle(TM) LMS from AWS Marketplace) (https://aws.amazon.com/marketplace/pp/B00NNZU2PM - not exactly this version, we're on older version v3.10)  

**What you expected:**

It's supposed to work.

**Comment by danmarsden** [comment]
"Bitnami" is a big warning sign there - Bitnami is not an approved/supported installer and they do a bunch of non-standard things that could be causing this - probably best to ask for help in the community forums.

In particular you should look at how your config.php file is set up, you should be manually specifying the wwwroot/dataroot variables with correct paths instead of the "guessing" that bitnami installers tend to do - it causes all sorts of problems.

I'm closing this here as it doesn't look like a "Bug" with our plugin, but a configuration issue with your installation.

If you want free help with configuring your moodle installation, you can ask for this in the moodle community forums on moodle.org (there are many posts from bitnami users with issues that might be relevant so do a search first)

Alternatively if you would like commercial level support to help - please drop us an email via the contact form on the Catalyst IT website.

Good luck!

**Comment by brendanheywood** [comment]
I've added that to the list of gotchas too:

https://github.com/catalyst/moodle-auth_saml2#bitnami-moodle
