### ISSUE TITLE
.extlib/simplesamlphp/modules/.gitignore ignores directories authYubiKey and metarefresh

### ISSUE THREAD

**Issue by danowar2k** [catalyst/moodle-auth_saml2#569]
We store our custom Moodle version in a git repository and update used 3rd party plugin versions in that repository.

We've now updated to https://moodle.org/plugins/auth_saml2/2021040100/24125 .
I've just now noticed when switching branches that there is a .gitignore file 

.extlib/simplesamlphp/modules/.gitignore which leads to our git ignoring the following directories:

* .extlib/simplesamlphp/modules/authYubiKey
* .extlib/simplesamlphp/modules/metarefresh

We deploy our Moodle from a git branch/tag. I'm now confused and wonder if those two directories should be present in our git repository and must be deployed as well or if this is a simple "We added these directories to gitignore but didn't remove them from tracking".

Please explain.

**Comment by danmarsden** [comment]
@danowar2k - .extlib/simplesamlphp is a copy of the upstream code from the simplesaml project. I see the "old" .gitignore did exlude that directory, but the one currently in core doesn't - I suspect something else in your config is ignoring ".gitignore" files in your system so you've ended up getting the "old" .gitignore file rather than the current one in this release.

I'm open to the idea of removing it from the .extlib/simplesamlphp/modules directory, but we prefer to include simplesamlphp "as-is" from upstream with the minimum number of changes as this make it easier to upgrade to the newer library when it is released.

**Comment by danowar2k** [comment]
I just found the release script of simplesamlphp which seems to remove the "modules/.gitignore" file in releases.

https://github.com/catalyst/moodle-auth_saml2/blob/ec90cd734517e63b0e2fde9ebf4ae33691752b75/.extlib/simplesamlphp/bin/build-release.sh#L67

So if I understand it correctly you're not dropping a released simplesamlphp in your plugin (because it would then not have the .gitignore files) but the upstream version, meaning you also clone simplesamlphp from source, at the moment probably the 1.18.8 tag. Right?

I'm gonna go look at my Moodle project's own .gitignore files, I'm currently confused because I don't remember doing any ignoring of other .gitignore files...we'll see.

Can you point me to the "old" .gitignore you mentioned? Looking myself just in case...

**Comment by danowar2k** [comment]
Okay, I've looked at our .gitignore files...

We basically have
/our-repo/.gitignore (only ignores .idea stuff and specifically named directories) (If requested I could post it)
/our-repo/moodle/.gitignore (Moodle's own gitignore, currently https://github.com/moodle/moodle/blob/v3.9.7/.gitignore)

And that was that.

We're upgrading auth_saml2 from https://moodle.org/plugins/auth_saml2/2019110701/20505 to https://moodle.org/plugins/auth_saml2/2021040100/24125.
So, basically, we're upgrading with this difference: https://github.com/catalyst/moodle-auth_saml2/compare/7b82651176a66d02566afc466c94b2bf51189e3b...c1756a0068d8e42aa70fc0698a437ca4519475cb (Yeah, that's why I requested git tags in the other issue).

It seems in that time extlib got moved to .extlib. The .extlib dir is not ignored by our outer gitignore files, nor are other gitignore files inside auth_saml2.

The .extlib/modules/.gitignore in the release https://moodle.org/plugins/auth_saml2/2021040100/24125 doesn't exclude AuthYubiKey, though.

**Comment by danowar2k** [comment]
If 

* .extlib/simplesamlphp/modules/authYubiKey
* .extlib/simplesamlphp/modules/metarefresh
should be included in a Moodle deployment, I propose adding an auth_saml2 .gitignore file which excludes those subdirectories from ignoring, although I'm not sure if that works. Maybe the inner .gitignore files override the outer ones, so that wouldn't work.

**Comment by danmarsden** [comment]
yes the last time we built this it was done from source rather than using their release - this allows us to remove some of the dependencies we don't need as per:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/.extlib/UPGRADE.md#remove-any-dependencies-we-dont-want

I'm not keen to modify the gitignore files or add new ones for simplesaml but I'm open to deleting the one in simplesaml/modules.

but... I'm still not convinced that's your problem because the existing gitignore is not doing anything with those files (the old one did) - I suspect something is going on with your local git config which has got you into this particular position.

**Comment by danmarsden** [comment]
- we have removed .gitignore files in the past too - if we remove it from the simplesamlphp lib, we'd need to tidy up our docs to specify the exact files we're removing in here:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/.extlib/UPGRADE.md#copy-into-auth_saml2

Pull request to remove that .gitignore file, and to imrpve that upgrade doc to specify the exact files being removed would be welcome!

**Comment by danowar2k** [comment]
> * we have removed .gitignore files in the past too - if we remove it from the simplesamlphp lib, we'd need to tidy up our docs to specify the exact files we're removing in here:
>   https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/.extlib/UPGRADE.md#copy-into-auth_saml2
> 
> Pull request to remove that .gitignore file, and to imrpve that upgrade doc to specify the exact files being removed would be welcome!

I'm not sure yet if that is needed. So, I'm first gonna attach our repo root .gitignore file content. And I'm gonna attach my git config, just to make sure. Any other files which could influence that behaviour?

I still would like to know what you mean by "the old one", can't you point me a URL to the gitignore in history you mean?

> the existing gitignore is not doing anything with those files

I'm gonna quote that file here and link to the version we're having...

This looks just like our version: https://github.com/catalyst/moodle-auth_saml2/blob/9a3be2b3c260d77c13d132553a58702bb056b770/.extlib/simplesamlphp/modules/.gitignore

In there it says to ignore all subdirectories in modules (`/*`) and then excludes several subdirs from that ignore pattern
(e.g. `!/exampleauth/`). But it doesn't exclude AuthYubiKey from ignoring.
That's why we can't add AuthYubiKey to our git repository. We don't have any rules excluding that directory or other gitignore files.

[gitignore.txt](https://github.com/catalyst/moodle-auth_saml2/files/6660908/gitignore.txt)

[gitconfig.txt](https://github.com/catalyst/moodle-auth_saml2/files/6660936/gitconfig.txt)

**Comment by danowar2k** [comment]
I looked at the https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/.extlib/UPGRADE.md#remove-any-dependencies-we-dont-want process and an idea I was having was could you use the composer-merge plugin to achieve this stuff? Although you need two vendor dirs here (yours and the simplesamlphp one) so that would probably not help. Also the .lock packages wouldn't be changed, even if you added "do not install package A and B", probably Composer would just throw an error about illogical dependencies or something.

Another way to process the released simplesamlphp packages could be downloading the release and then removing the vendor directories you don't need using rm? But that would probably be more work because those packages depend on other packages, so it wouldn't be enough removing only the main packages...damn.

**Comment by danowar2k** [comment]
And the final thing for now I just discovered:

`# Explicitly include modules that ship with simplesamlphp`

is in that gitignore file. So if `AuthYubiKey` and `metarefresh` aren't shipped with simplesamlphp, you do not need those modules, either, or do you? And if you don't need those in auth_saml2, you could also remove those directories in your releases...

So your upgrade process could be adapted to remove those directories...? Maybe a upgrade script could be added to the .extlib directory? It seems like the stuff in the UPGRADE.md could be mostly transformed into one or more scripts...

**Comment by danmarsden** [comment]
Thanks @danowar2k - I've just tidied up our upgrade docs for simplesamlphp, referring to the build.sh file you mentioned and also removing the .gitignore (and a few other files) - which should tidy this up for you. Depending on the state of your codebase you might want to remove the old saml2 plugin completely, commit, and then re-add a new commit/merge/submodule/subtree or whatever method you're using.

flagging this as closed now! - thanks.

**Comment by danowar2k** [comment]
Thanks, locally I'll just remove the .gitignore for our version and add all the missing files to our git now. As this change will ripple into next releases we won't have this problem/confusion again I think.

Well, this exact problem anyway ;-)

**Comment by davosmith** [comment]
@danmarsden just flagging up that this issue still seems to exist in the latest zip file downloaded from Moodle.org ( https://moodle.org/plugins/auth_saml2 ).

saml2/.extlib/simplesamlphp/modules/ contains a lot of sub-directories, the majority of which are excluded from adding to git via .gitignore.

This causes problems in the following scenario:
* Download the zip file, unzip it to the correct location
* Commit the directory to the local Moodle repo
* Switch to another branch

Expected:
* Directory: auth/saml2 is no longer present locally

Actual:
* Directory: auth/saml2 still present (due to the .extlib/simplesamlphp/modules directory still being present)
* Error about missing version.php in auth_saml2 (in the Moodle UI)

This fairly trivial to fix locally (just delete the auth/saml2 directory after switching branches), but is quite annoying when using automatic scripts to manage plugin installation across multiple Moodle repositories ...

**Comment by danmarsden** [comment]
yeah - feel free to send a PR through to add remove the file from the current build, but also add the file to the test here:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/tests/simplesamlphp_upgrade_test.php#L39

that way we don't do it again next time we upgrade simplesaml lib. :-)

**Comment by davosmith** [comment]
I've opened a pull request to fix this.

I note the unit test you linked to appeared to be broken, so I've fixed that (as well as extending it to cover the .gitignore file) - please let me know if I've missed something subtle about the test ...
