### ISSUE TITLE
Logged in Session is shared globally

### ISSUE THREAD

**Issue by RaphaelSchein** [catalyst/moodle-auth_saml2#670]
Hi,

I set up your plugin with Moodle and Auth0 as IDP in a test environment over the weekend and everything is running great, except for the fact that when I log in to computer 1 via SAML2 and then I also try to log in from computer 2 via SAML2 I am automatically logged into Computer 1's account. I also tried other IPDs and the problem existed

**Comment by danmarsden** [comment]
sounds more like an issue with your Auth0 IDP - we havne't seen that behaviour before with the saml2 plugin.

**Comment by brendanheywood** [comment]
hi @RaphaelSchein,

Adding to what Dan said: an easy way to narrow down where the bug is to install a saml tracer browser plugin like this one:

https://github.com/SimpleSAMLphp/SAML-tracer

Trace the saml assertions and if on computer 2 the username coming from the IdP is the same as what you've logged into on computer 1 then it is definitely an IdP issue. 

I'll close this issue, but if you can clearly demonstrate that your IdP is returning an identity B and the saml2 plugin is ignoring that and logging you in as another identity A then this would be a major security issue. If that is the case please do not comment here, contact us privately with the full details including the details of the cookies, traces, idp metadata, your config etc to security@catalyst-au.net
