### ISSUE TITLE
Consider ditching the internally save sp metadata xml file

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_saml2#683]
**What happened?**

This file only really exists as a cache but it isn't slow to generate the file, and having the cache means there are a class of problems which are solved by regenerating it. Given how infrequently this url is actually scraped I think we can just ditch the cache rather than fixing the edge case cache invalidation logic.

**What you expected:**
* [ ] make the cli just live
* [ ] add a cli export just in case we need it and can't easily get outside and back in
* [ ] There is a chance we did it this way specifically to help refreshes from prod to uat and stage and so prod would need multiple sp's - need to test and document this more

**Comment by sammarshallou** [comment]
Just to note, I think this cache might be responsible for an issue we have at the OU where we periodically recreate our acceptance test server (from a copy of live data, with changes automatically applied to make the setup right for test). I thought we copied all the necessary files and we definitely purge caches but even so, in the new acceptance test server, saml2 doesn't work and you have to log in using manual login and do 'save changes' on the saml2 admin page without changing anything, which fixes it.

We were thinking of making a temporary workaround CLI as part of our test deployment that does the same thing that the custom admin setting does when you save that page (since presumably this is what fixes it), i.e. 

$idpmetadata = new \auth_saml2\admin\setting_idpmetadata();
$idpmetadata->validate(get_config('auth_saml2', 'idpmetadata'));

We haven't yet tested this approach but seems like it ought to work.
