### ISSUE TITLE
2022051700 version isn't on moodle.org plugins

### ISSUE THREAD

**Issue by okigye** [catalyst/moodle-auth_saml2#697]
**What happened?**

Version was bumped to 2022051700 but not released to https://moodle.org/plugins/auth_saml2/. Isn't it automatical by https://github.com/catalyst/moodle-auth_saml2/actions/workflows/moodle-release.yml ?

**What you expected:**
After the merge of the Simplesaml 1.91.5 branch, the new version appearing on the moodle plugins page, and in our moodle instance as an update. 

**FTR:**
I know, that I can git pull the source from here, but I when the code will be released, would be there an another version bump? So the in between changes will be avaiable via moodle plugin update.

Thanks in advance.
Oki

**Comment by danmarsden** [comment]
Hi @okigye - you will need to wait for us to publish again - our auto-deploy pipeline will only push to the plugins db under certain conditions (a push that includes a change to version.php) - the last update of version.php was done through a merge.

The best way to ensure you use an updated version of our plugins would be to use github rather than the moodle.org plugins db - if you wan to use the plugins db, you'll just have to patiently wait for us to push a plugin update through.. (we don't give any guarantees on time frames for this.)
